### ISSUE TITLE
Convert Gamemode names by default 

### ISSUE THREAD

**Issue by FlashHit** [kaloczikvn/VU-Loading#4]
There is a mapping for maplist gamemode names to display gamemode names. So custom maplist gamemode names won’t work.
For this I would like the names to automatically convert.
Examples: `MyCustomGamemode0` -> `My Custom Gamemode`
`MyCustomGamemode1` -> `My Custom Gamemode #1`
`BFLAG0` -> `BFLAG`

so add a space in front of capital letters that come after a lower case letter.
add a space and a `#` in front of numbers, except if the number is a 0.

**Comment by kaloczikvn** [comment]
Will fix this issue with: #5
